const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  preflight: () => ipcRenderer.invoke("preflight"),
  requestMicAccess: () => ipcRenderer.invoke("request-mic-access"),
  openPrivacySettings: (target) => ipcRenderer.invoke("open-privacy-settings", target),
  listDevices: () => ipcRenderer.invoke("list-devices"),
  getPresets: () => ipcRenderer.invoke("get-presets"),
  savePresets: (data) => ipcRenderer.invoke("save-presets", data),
  resetApp: () => ipcRenderer.invoke("reset-app"),
  pickAudio: () => ipcRenderer.invoke("pick-audio"),
  pickOutDir: () => ipcRenderer.invoke("pick-out-dir"),
  startRecording: (opts) => ipcRenderer.invoke("start-recording", opts),
  stopRecording: () => ipcRenderer.invoke("stop-recording"),
  listPendingRecordings: () => ipcRenderer.invoke("list-pending-recordings"),
  removePendingRecording: (id) => ipcRenderer.invoke("remove-pending-recording", id),
  processAudio: (opts) => ipcRenderer.invoke("process-audio", opts),
  cancelProcess: () => ipcRenderer.invoke("cancel-process"),
  getModels: () => ipcRenderer.invoke("models"),
  downloadModels: (opts) => ipcRenderer.invoke("download-models", opts),
  cancelModelDownload: () => ipcRenderer.invoke("cancel-model-download"),
  backendStatus: () => ipcRenderer.invoke("backend-status"),
  installBackend: () => ipcRenderer.invoke("install-backend"),
  cancelInstallBackend: () => ipcRenderer.invoke("cancel-install-backend"),
  uninstallBackend: () => ipcRenderer.invoke("uninstall-backend"),
  reveal: (p) => ipcRenderer.invoke("reveal", p),
  renameSpeakers: (notePath, map) => ipcRenderer.invoke("rename-speakers", { notePath, map }),
  listHistory: (outDir) => ipcRenderer.invoke("list-history", outDir),
  readNote: (notePath) => ipcRenderer.invoke("read-note", notePath),
  paraCreateVault: (cfg) => ipcRenderer.invoke("para-create-vault", cfg),
  paraTree: (root) => ipcRenderer.invoke("para-tree", root),
  paraClassify: (arg) => ipcRenderer.invoke("para-classify", arg),
  paraExtract: (notePath) => ipcRenderer.invoke("para-extract", notePath),
  paraFile: (args) => ipcRenderer.invoke("para-file", args),
  paraReindex: (root) => ipcRenderer.invoke("para-reindex", { root }),
  paraSearch: (root, messages) => ipcRenderer.invoke("para-search", { root, messages }),
  cancelSearch: () => ipcRenderer.invoke("cancel-search"),
  notifyRecordingState: (recording) => ipcRenderer.send("recording-state", recording),

  onRecordEvent: (cb) => ipcRenderer.on("record-event", (_e, ev) => cb(ev)),
  onProcessEvent: (cb) => ipcRenderer.on("process-event", (_e, ev) => cb(ev)),
  onParaReindexEvent: (cb) => ipcRenderer.on("para-reindex-event", (_e, ev) => cb(ev)),
  onModelDownloadEvent: (cb) => ipcRenderer.on("download-models-event", (_e, ev) => cb(ev)),
  onInstallBackendEvent: (cb) => ipcRenderer.on("install-backend-event", (_e, ev) => cb(ev)),
  onTrayRecordToggle: (cb) => ipcRenderer.on("tray-record-toggle", () => cb()),
});
